In [6]:
import pandas as pd
df = pd.read_csv("../data/diamond-v0.csv")
df.rename(columns={
    'x (Premium)': 'x',
    'z (Very Good)': 'z',
    'y (Good)': 'y'
}, inplace=True)
df.copy()

             cut color clarity  carat  depth  table  price     x     z     y
0           Fair     E     VS2   0.22   65.1   61.0    337  3.87  2.49  3.78
1           Fair     E     SI2   0.86   55.1   69.0   2757  6.45  3.52  6.33
2           Fair     F     SI2   0.96   66.3   62.0   2759  6.27  4.07  5.95
3           Fair     F     VS2   0.70   64.5   57.0   2762  5.57  3.58  5.53
4           Fair     F     VS2   0.70   65.3   55.0   2762  5.63  3.66  5.58
...          ...   ...     ...    ...    ...    ...    ...   ...   ...   ...
53935  Very Good     E     VS2   0.70   62.8   60.0   2755  5.59  3.53  5.65
53936  Very Good     D     VS1   0.70   63.1   59.0   2755  5.67  3.55  5.58
53937  Very Good     E     VS2   0.70   60.5   59.0   2757  5.71  3.47  5.76
53938  Very Good     E     VS2   0.70   61.2   59.0   2757  5.69  3.49  5.72
53939  Very Good     D     SI1   0.70   62.8   60.0   2757  5.66  3.56  5.68

[53940 rows x 10 columns]

In [7]:
df.to_csv("../data/diamond_cleaned.csv", index=False)