In [15]:
import pandas as pd
from sklearn.model_selection import train_test_split
import xgboost as xgb
from sklearn.metrics import mean_squared_error

In [16]:
df = pd.read_csv("../data/processed-v0.csv")
df

,Unnamed: 0,cut,color,clarity,carat,depth,table,price,x (Premium),z (Very Good),y (Good)
0,0,0,1,5,0.22,65.1,61.0,337,3.87,2.49,3.78
1,1,0,1,3,0.86,55.1,69.0,2757,6.45,3.52,6.33
2,2,0,2,3,0.96,66.3,62.0,2759,6.27,4.07,5.95
3,3,0,2,5,0.70,64.5,57.0,2762,5.57,3.58,5.53
4,4,0,2,5,0.70,65.3,55.0,2762,5.63,3.66,5.58
...,...,...,...,...,...,...,...,...,...,...,...
53935,53935,4,1,5,0.70,62.8,60.0,2755,5.59,3.53,5.65
53936,53936,4,0,4,0.70,63.1,59.0,2755,5.67,3.55,5.58
53937,53937,4,1,5,0.70,60.5,59.0,2757,5.71,3.47,5.76
53938,53938,4,1,5,0.70,61.2,59.0,2757,5.69,3.49,5.72
53939,53939,4,0,2,0.70,62.8,60.0,2757,5.66,3.56,5.68

In [17]:
# Define features (X) and target (y)
X = df.drop(columns=["price"])
y = df["price"]

# Split into 80% training and 20% testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training set size: {X_train.shape}")
print(f"Test set size: {X_test.shape}")

Training set size: (43152, 10)
Test set size: (10788, 10)

In [18]:
xgb_reg = xgb.XGBRegressor(
    n_estimators=200,      # Number of trees
    learning_rate=0.05,    # Step size shrinkage
    max_depth=4,           # Maximum depth of each tree
    subsample=0.8,         # Fraction of training samples used per tree
    colsample_bytree=0.8,  # Fraction of features used per tree
    random_state=42
)

# Train the model
xgb_reg.fit(X_train, y_train)

# Make predictions
y_pred = xgb_reg.predict(X_test)
y_pred

array([1926.1937 ,  518.79346, 2328.7222 , ..., 6855.455  ,  918.6519 ,
        883.3681 ], shape=(10788,), dtype=float32)

In [19]:
from sklearn.metrics import r2_score


# Calculate R-squared
r2 = r2_score(y_test, y_pred)
print(f"R-squared (R²): {r2}")

R-squared (R²): 0.9826804399490356

In [20]:
import joblib

# Save the model to a file
joblib.dump(xgb_reg, "xgb_reg_model.pkl")

print("Model saved as 'xgb_reg_model.pkl'")

Model saved as 'xgb_reg_model.pkl'